- name: Start kibana container
  docker_container:
    name: "{{ kibana_hostname }}"
    image: "{{ kibana_image }}"
    env:
      ELASTICSEARCH_HOSTS: "http://{{ elasticsearch_hostname }}:9200"
      ELASTICSEARCH_USERNAME: "kibana"
      ELASTICSEARCH_PASSWORD: "{{ kibana_password }}"
      ports:
      - "0.0.0.0:5601:5601/tcp"
      log_driver: "{{ log_driver }}"
      log_options:
        max-size: "{{ log_max-size }}"
        max-file: "{{ log_max-file }}"
