elasticsearch_image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
elasticsearch_hostname: es01
elasticsearch_conf_dir: /usr/share/elasticsearch

kibana_image: docker.elastic.co/kibana/kibana:7.15.0
kibana_hostname: ki01

logstash_image: docker.elastic.co/logstash/logstash:7.15.0
logstash_hostname: lo01
logstash_conf_dir: /usr/share/logstash

elastic_password: "{{ vault_elastic_password }}"
kibana_password: "{{ vault_kibana_password }}"